// x86_64-pc
// Generated by build.rs, DO NOT edit!
#![allow(dead_code)]

pub const KERNEL_BASE_PADDR: usize = 0x20_0000;
pub const KERNEL_BASE_VADDR: usize = 0xffff_ff80_0020_0000;
pub const PHYS_MEMORY_BASE: usize = 0;
pub const PHYS_MEMORY_SIZE: usize = 0x800_0000;
#[rustfmt::skip]
pub const MMIO_REGIONS: &[(usize, usize)] = &[
    (0xfec0_0000, 0x1000),
    (0xfed0_0000, 0x1000),
    (0xfee0_0000, 0x1000),
];
